# Model configuration
dinov2:
  # Path to pretrained DINOv2 model
  # For Kaggle: '/kaggle/input/dinov2/pytorch/base/1/'
  # For local: specify your local path
  
  model_path: facebook/dinov2-base #/kaggle/input/dinov2/pytorch/base/1/
  processor_path: facebook/dinov2-base #/kaggle/input/dinov2/pytorch/base/1/

lasso:
  alpha: 1.0  # Regularization strength
  n_targets: 5
  n_folds: 5

# Model output
save_path: models/lasso_ensemble.pkl

