defaults:
  - data: default
  - model: two_stream_tiled_dinov2large
  - training: mlps_only
  - inference: default
  - augmentation: default
  - logging: wandb
  - _self_

# Global settings
seed: 42
device: cuda

exp_name: our_split_mlps_only_dinov2large_17_23_concat_fusion_feature_layers_cls_mean_pooling_qualityweightedtiles_w_semantic_concat_wembed_wmixuo_wema_newtrainaugs_gptaugs

# Output directories
output_dir: outputs
checkpoint_dir: checkpoints/${logging.experiment_name}

# Hydra configuration
hydra:
  run:
    dir: ${output_dir}/${now:%Y-%m-%d_%H-%M-%S}
 