defaults:
  - data: default
  - model: two_stream_tiled_dinov2base
  - training: mlps_only
  - inference: default
  - augmentation: default
  - logging: wandb
  - _self_

# Global settings
seed: 42
device: cuda

exp_name: our_split_mlps_only_dinov2base_baseline_7_11_cls_mean_pooling_wsemantic

# Output directories
output_dir: outputs
checkpoint_dir: checkpoints/${logging.experiment_name}

# Hydra configuration
hydra:
  run:
    dir: ${output_dir}/${now:%Y-%m-%d_%H-%M-%S}
 